/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users/{identifier}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user data */
    get: operations['getUserData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{identifier}/matches': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user matches */
    get: operations['getUserMatches'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{identifier1}/versus/{identifier2}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get versus stats */
    get: operations['getVersusStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{identifier1}/versus/{identifier2}/matches': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get versus matches */
    get: operations['getVersusMatches'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{identifier}/seasons': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all user season results */
    get: operations['getUserSeasons'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{identifier}/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user's live match data
     * @description Returns real-time match data from the private room the player is in.
     */
    get: operations['getUserLiveData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/matches': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get recent matches */
    get: operations['getRecentMatches'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/matches/{match_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get match info */
    get: operations['getMatchInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get online players and public live matches */
    get: operations['getPublicLiveData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/leaderboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get elo leaderboard */
    get: operations['getEloLeaderboard'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/phase-leaderboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get season phase points leaderboard */
    get: operations['getPhaseLeaderboard'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/record-leaderboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get season best time leaderboard */
    get: operations['getRecordLeaderboard'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/weekly-race': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current weekly race leaderboard */
    get: operations['getCurrentWeeklyRace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/weekly-race/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a specific weekly race leaderboard */
    get: operations['getWeeklyRaceById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/status-page/heartbeat/mcsrranked': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get service heartbeats
     * @description Returns the 100 most recent public heartbeats for each service on the MCSR Ranked status page,
     *     plus each service's rolling 24-hour uptime ratio.
     *
     *     Monitor IDs currently map to `2` Game Server, `3` API, `4` Store, and `5` Wiki.
     *     Heartbeat status values are `0` down, `1` up, `2` pending, and `3` maintenance.
     */
    get: operations['getStatusPageHeartbeats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    StatusHeartbeatResponse: {
      /** @description Heartbeat history keyed by monitor ID, ordered oldest to newest. */
      heartbeatList: {
        [key: string]: components['schemas']['StatusHeartbeat'][];
      };
      /** @description Rolling 24-hour uptime ratios keyed as `{monitorId}_24`. */
      uptimeList: {
        [key: string]: number;
      };
    };
    StatusHeartbeat: {
      /**
       * @description Heartbeat status. `0` down, `1` up, `2` pending, or `3` maintenance.
       * @enum {integer}
       */
      status: 0 | 1 | 2 | 3;
      /**
       * @description Heartbeat time in `YYYY-MM-DD HH:mm:ss` format.
       * @example 2026-07-21 13:11:27
       */
      time: string;
      /**
       * @description Public message; currently redacted to an empty string.
       * @example
       */
      msg: string;
      /**
       * @description Response time in milliseconds, or `null` when unavailable.
       * @example 85
       */
      ping: number | null;
    };
    SuccessEnvelope: {
      /** @enum {string} */
      status: 'success';
    };
    ErrorResponse: {
      /** @enum {string} */
      status: 'error';
      data:
        | string
        | {
            [key: string]: unknown;
          }
        | null;
    };
    UserResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['UserDetails'];
    };
    MatchListResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['MatchInfo'][];
    };
    VersusResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['VersusStats'];
    };
    UserSeasonsResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['UserSeasonSummary'];
    };
    UserLiveResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['UserLiveData'];
    };
    MatchDetailResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['MatchInfo'];
    };
    PublicLiveResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['PublicLiveData'];
    };
    LeaderboardResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['Leaderboard'];
    };
    PhaseLeaderboardResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['PhaseLeaderboard'];
    };
    RecordLeaderboardResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['RecordLeaderboardEntry'][];
    };
    WeeklyRaceResponse: components['schemas']['SuccessEnvelope'] & {
      data: components['schemas']['WeeklyRace'];
    };
    /** @description UUID, nickname, or `discord.{id}`. */
    UserIdentifier: string;
    /** @description Epoch timestamp in seconds. */
    Date: number;
    /** @description Duration in milliseconds. */
    Time: number;
    /**
     * @description Match type identifier.
     * @enum {integer}
     */
    MatchType: 1 | 2 | 3 | 4;
    UserProfile: {
      /** @description User UUID without dashes. */
      uuid: string;
      nickname: string;
      roleType: number;
      eloRate: number | null;
      eloRank: number | null;
      country: string | null;
    };
    Achievement: {
      id: string;
      date: components['schemas']['Date'];
      data: string[];
      level: number;
      value: number | null;
      goal: number | null;
    };
    MatchSeed: {
      id: string | null;
      overworld: string | null;
      nether: string | null;
      endTowers: number[];
      variations: string[];
    };
    WeeklyRaceSeed: {
      overworld: string;
      nether: string;
      theEnd: string;
      rng: string;
      flags: number;
    };
    RankedCasualStat: {
      ranked: number | null;
      casual: number | null;
    };
    StatisticCategoryMap: {
      [key: string]: components['schemas']['RankedCasualStat'];
    };
    UserConnection: {
      id: string;
      name: string;
    };
    SeasonStanding: {
      eloRate: number | null;
      eloRank: number | null;
      phasePoint: number;
    };
    SeasonPhaseResult: {
      phase: number;
      eloRate: number;
      eloRank: number;
      point: number;
    };
    SeasonResultDetailed: {
      last: components['schemas']['SeasonStanding'];
      highest: number | null;
      lowest: number | null;
      phases: components['schemas']['SeasonPhaseResult'][];
    };
    WeeklyRaceResult: {
      id: number;
      time: components['schemas']['Time'];
      rank: number;
    };
    UserDetails: components['schemas']['UserProfile'] & {
      achievements: {
        display: components['schemas']['Achievement'][];
        total: components['schemas']['Achievement'][];
      };
      timestamp: {
        firstOnline: components['schemas']['Date'];
        lastOnline: components['schemas']['Date'];
        lastRanked: components['schemas']['Date'];
        nextDecay: number | null;
      };
      statistics: {
        season: components['schemas']['StatisticCategoryMap'];
        total: components['schemas']['StatisticCategoryMap'];
      };
      connections: {
        [key: string]: components['schemas']['UserConnection'];
      };
      seasonResult: components['schemas']['SeasonResultDetailed'] | null;
      weeklyRaces: components['schemas']['WeeklyRaceResult'][];
    };
    UserSeasonSummary: components['schemas']['UserProfile'] & {
      seasonResults: {
        [key: string]: components['schemas']['SeasonResultDetailed'];
      };
    };
    MatchResult: {
      uuid: string | null;
      time: components['schemas']['Time'];
    };
    MatchRank: {
      season: number | null;
      allTime: number | null;
    };
    MatchChange: {
      uuid: string;
      change: number | null;
      eloRate: number | null;
    };
    MatchVod: {
      uuid: string;
      url: string;
      startsAt: components['schemas']['Date'];
    };
    CompletionEntry: {
      uuid: string;
      time: components['schemas']['Time'];
    };
    TimelineEntry: {
      uuid: string;
      time: components['schemas']['Time'];
      type: string;
    };
    MatchInfo: {
      id: number;
      type: components['schemas']['MatchType'];
      season: number;
      category?: string | null;
      gameMode?: string | null;
      date: components['schemas']['Date'];
      players: components['schemas']['UserProfile'][];
      spectators: components['schemas']['UserProfile'][];
      seed?: components['schemas']['MatchSeed'] | null;
      result: components['schemas']['MatchResult'];
      forfeited: boolean;
      decayed: boolean;
      rank: components['schemas']['MatchRank'];
      changes: components['schemas']['MatchChange'][];
      vod?: components['schemas']['MatchVod'][];
      completions?: components['schemas']['CompletionEntry'][];
      timelines?: components['schemas']['TimelineEntry'][];
      tag?: string | null;
      replayExist?: boolean;
      beginner: boolean;
      botSource: string | null;
      seedType?: string | null;
      bastionType?: string | null;
    };
    VersusResultMap: {
      [key: string]: number;
    };
    VersusStats: {
      players: components['schemas']['UserProfile'][];
      results: {
        ranked: components['schemas']['VersusResultMap'];
        casual: components['schemas']['VersusResultMap'];
      };
      changes: {
        [key: string]: number;
      };
    };
    UserLiveData: {
      lastId: number | null;
      type: components['schemas']['MatchType'];
      /** @enum {string} */
      status: 'idle' | 'counting' | 'generate' | 'ready' | 'running' | 'done';
      time: components['schemas']['Time'];
      players: components['schemas']['UserProfile'][];
      spectators: components['schemas']['UserProfile'][];
      timelines: components['schemas']['TimelineEntry'][];
      completions: components['schemas']['CompletionEntry'][];
    };
    LiveTimelineSnapshot: {
      time: components['schemas']['Time'];
      type: string;
    };
    LiveMatchPlayerData: {
      liveUrl: string | null;
      timeline: components['schemas']['LiveTimelineSnapshot'] | null;
    };
    LiveMatch: {
      currentTime: components['schemas']['Time'];
      players: components['schemas']['UserProfile'][];
      data: {
        [key: string]: components['schemas']['LiveMatchPlayerData'];
      };
    };
    PublicLiveData: {
      players: number;
      liveMatches: components['schemas']['LiveMatch'][];
    };
    LeaderboardSeason: {
      startsAt: components['schemas']['Date'];
      endsAt: components['schemas']['Date'];
      number: number;
    };
    UserProfileWithSeasonResult: components['schemas']['UserProfile'] & {
      seasonResult: components['schemas']['SeasonStanding'];
    };
    Leaderboard: {
      season: components['schemas']['LeaderboardSeason'];
      users: components['schemas']['UserProfileWithSeasonResult'][];
    };
    PhaseInfo: {
      endsAt: number | null;
      number: number | null;
      season: number;
    };
    UserProfileWithPredictedPoints: components['schemas']['UserProfileWithSeasonResult'] & {
      predPhasePoint: number;
    };
    PhaseLeaderboard: {
      phase: components['schemas']['PhaseInfo'];
      users: components['schemas']['UserProfileWithPredictedPoints'][];
    };
    RecordLeaderboardEntry: {
      rank: number;
      id: number;
      season: number;
      date: components['schemas']['Date'];
      time: components['schemas']['Time'];
      user: components['schemas']['UserProfile'];
      seed: components['schemas']['MatchSeed'];
    };
    WeeklyRaceEntry: {
      rank: number;
      player: components['schemas']['UserProfile'];
      time: components['schemas']['Time'];
      replayExist: boolean;
    };
    WeeklyRace: {
      id: number;
      seed: components['schemas']['WeeklyRaceSeed'];
      endsAt: components['schemas']['Date'];
      leaderboard: components['schemas']['WeeklyRaceEntry'][];
    };
  };
  responses: {
    /** @description Requested data was not found or the request payload was invalid. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description One or more parameters were invalid. */
    WrongParameters: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Rate limit exceeded. */
    TooManyRequests: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
  };
  parameters: {
    /** @description User identifier. Can be a UUID, nickname, or `discord.{id}`. */
    IdentifierParam: components['schemas']['UserIdentifier'];
    /** @description First user identifier. Can be a UUID, nickname, or `discord.{id}`. */
    Identifier1Param: components['schemas']['UserIdentifier'];
    /** @description Second user identifier. Can be a UUID, nickname, or `discord.{id}`. */
    Identifier2Param: components['schemas']['UserIdentifier'];
    /** @description Match ID. */
    MatchIdParam: number;
    /** @description Weekly race number. */
    WeeklyRaceIdParam: number;
    /** @description Season number. Defaults to the current season. */
    SeasonParam: number;
    /** @description Season number. If set to `0`, the API uses the current season. If omitted, all seasons are combined. */
    SeasonZeroCurrentParam: number;
    /** @description Match list cursor. Returns matches before this match ID. */
    BeforeParam: number;
    /** @description Match list cursor. Returns matches after this match ID. */
    AfterParam: number;
    /** @description Number of matches to return. */
    CountParam: number;
    /** @description Match list sort option. */
    SortParam: 'newest' | 'oldest' | 'fastest' | 'slowest';
    /** @description Filter by match type. */
    MatchTypeParam: components['schemas']['MatchType'];
    /** @description Lowercased ISO 3166-1 alpha-2 country code. */
    CountryParam: string;
    /** @description Filter matches by tag. */
    TagParam: string;
    /** @description Include decay matches. The API accepts this as a boolean-style query parameter. */
    IncludeDecayParam: boolean;
    /** @description Exclude decay matches. */
    ExcludeDecayParam: boolean;
    /** @description Get predicted phase points. Must be `true` or `false` (the API also accepts `1` or `0`). Only works for the current season. */
    PredictedParam: boolean;
    /** @description Return only the fastest run for each runner. */
    DistinctParam: boolean;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getUserData: {
    parameters: {
      query?: {
        /** @description Season number. Defaults to the current season. */
        season?: components['parameters']['SeasonParam'];
      };
      header?: never;
      path: {
        /** @description User identifier. Can be a UUID, nickname, or `discord.{id}`. */
        identifier: components['parameters']['IdentifierParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getUserMatches: {
    parameters: {
      query?: {
        /** @description Match list cursor. Returns matches before this match ID. */
        before?: components['parameters']['BeforeParam'];
        /** @description Match list cursor. Returns matches after this match ID. */
        after?: components['parameters']['AfterParam'];
        /** @description Match list sort option. */
        sort?: components['parameters']['SortParam'];
        /** @description Number of matches to return. */
        count?: components['parameters']['CountParam'];
        /** @description Filter by match type. */
        type?: components['parameters']['MatchTypeParam'];
        /** @description Season number. Defaults to the current season. */
        season?: components['parameters']['SeasonParam'];
        /** @description Exclude decay matches. */
        excludedecay?: components['parameters']['ExcludeDecayParam'];
      };
      header?: never;
      path: {
        /** @description User identifier. Can be a UUID, nickname, or `discord.{id}`. */
        identifier: components['parameters']['IdentifierParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User matches returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MatchListResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getVersusStats: {
    parameters: {
      query?: {
        /** @description Season number. Defaults to the current season. */
        season?: components['parameters']['SeasonParam'];
      };
      header?: never;
      path: {
        /** @description First user identifier. Can be a UUID, nickname, or `discord.{id}`. */
        identifier1: components['parameters']['Identifier1Param'];
        /** @description Second user identifier. Can be a UUID, nickname, or `discord.{id}`. */
        identifier2: components['parameters']['Identifier2Param'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versus statistics returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersusResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getVersusMatches: {
    parameters: {
      query?: {
        /** @description Match list cursor. Returns matches before this match ID. */
        before?: components['parameters']['BeforeParam'];
        /** @description Match list cursor. Returns matches after this match ID. */
        after?: components['parameters']['AfterParam'];
        /** @description Number of matches to return. */
        count?: components['parameters']['CountParam'];
        /** @description Filter by match type. */
        type?: components['parameters']['MatchTypeParam'];
        /** @description Season number. Defaults to the current season. */
        season?: components['parameters']['SeasonParam'];
      };
      header?: never;
      path: {
        /** @description First user identifier. Can be a UUID, nickname, or `discord.{id}`. */
        identifier1: components['parameters']['Identifier1Param'];
        /** @description Second user identifier. Can be a UUID, nickname, or `discord.{id}`. */
        identifier2: components['parameters']['Identifier2Param'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versus matches returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MatchListResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getUserSeasons: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User identifier. Can be a UUID, nickname, or `discord.{id}`. */
        identifier: components['parameters']['IdentifierParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User season history returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserSeasonsResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getUserLiveData: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User identifier. Can be a UUID, nickname, or `discord.{id}`. */
        identifier: components['parameters']['IdentifierParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Live match data returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserLiveResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getRecentMatches: {
    parameters: {
      query?: {
        /** @description Match list cursor. Returns matches before this match ID. */
        before?: components['parameters']['BeforeParam'];
        /** @description Match list cursor. Returns matches after this match ID. */
        after?: components['parameters']['AfterParam'];
        /** @description Number of matches to return. */
        count?: components['parameters']['CountParam'];
        /** @description Filter by match type. */
        type?: components['parameters']['MatchTypeParam'];
        /** @description Filter matches by tag. */
        tag?: components['parameters']['TagParam'];
        /** @description Season number. Defaults to the current season. */
        season?: components['parameters']['SeasonParam'];
        /** @description Include decay matches. The API accepts this as a boolean-style query parameter. */
        includedecay?: components['parameters']['IncludeDecayParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recent matches returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MatchListResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getMatchInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Match ID. */
        match_id: components['parameters']['MatchIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Match details returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MatchDetailResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getPublicLiveData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public live data returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicLiveResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getEloLeaderboard: {
    parameters: {
      query?: {
        /** @description Season number. Defaults to the current season. */
        season?: components['parameters']['SeasonParam'];
        /** @description Lowercased ISO 3166-1 alpha-2 country code. */
        country?: components['parameters']['CountryParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Elo leaderboard returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LeaderboardResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getPhaseLeaderboard: {
    parameters: {
      query?: {
        /** @description Season number. Defaults to the current season. */
        season?: components['parameters']['SeasonParam'];
        /** @description Lowercased ISO 3166-1 alpha-2 country code. */
        country?: components['parameters']['CountryParam'];
        /** @description Get predicted phase points. Must be `true` or `false` (the API also accepts `1` or `0`). Only works for the current season. */
        predicted?: components['parameters']['PredictedParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Phase points leaderboard returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PhaseLeaderboardResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getRecordLeaderboard: {
    parameters: {
      query?: {
        /** @description Season number. If set to `0`, the API uses the current season. If omitted, all seasons are combined. */
        season?: components['parameters']['SeasonZeroCurrentParam'];
        /** @description Return only the fastest run for each runner. */
        distinct?: components['parameters']['DistinctParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Record leaderboard returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecordLeaderboardResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getCurrentWeeklyRace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Weekly race returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WeeklyRaceResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getWeeklyRaceById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Weekly race number. */
        id: components['parameters']['WeeklyRaceIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Weekly race returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WeeklyRaceResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['WrongParameters'];
      429: components['responses']['TooManyRequests'];
    };
  };
  getStatusPageHeartbeats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public heartbeat history and 24-hour uptime ratios returned successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusHeartbeatResponse'];
        };
      };
    };
  };
}
